apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-demo-gl
  template:
    metadata: 
      labels:
        app: argocd-demo
    spec:
      containers:
      - name: nginx
        image: quay.io/yahoon/argocd-demo:v1
        ports:
        - containerPort: 80

