stages:
  - build
  - test
  - push

default:
  tags:
    - shared-podman
  image: quay.io/containers/podman:latest
  # before_script:
  #   - chmod -R go-w ${PWD}
  #   - git config --global --add safe.directory ${PWD}

variables:
  IMAGE_NAME: quay.io/yahoon/argocd-demo-gl
  CONTAINERFILE_PATH: container-image/argocd-demo/Containerfile
  CONTEXT_PATH: container-image/argocd-demo
  CONTAINER_NAME: argocd-demo-test

build:
  stage: build
  before_script:
    - IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - DEV_IMAGE=${IMAGE_NAME}:dev-${IMAGE_TAG}
    - echo "DEV_IMAGE=$DEV_IMAGE"
  script:
    # Build the image
    - echo "=== BUILD ==="
    - podman build -f $CONTAINERFILE_PATH -t $DEV_IMAGE $CONTEXT_PATH
    - echo "=== PUSH DEV ==="
    - echo "$QUAY_PASSWORD" | podman login quay.io -u "$QUAY_USERNAME" --password-stdin
    - podman push $DEV_IMAGE
    - echo "✅ Pushed $DEV_IMAGE"
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

test:
  stage: test
  before_script:
    - IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - DEV_IMAGE=${IMAGE_NAME}:dev-${IMAGE_TAG}
    - RC_IMAGE=${IMAGE_NAME}:rc-${IMAGE_TAG}
    - echo "DEV_IMAGE=$DEV_IMAGE"
    - echo "RC_IMAGE=$RC_IMAGE"
  script:
    - echo "=== PULL DEV IMAGE ==="
    - echo "$QUAY_PASSWORD" | podman login quay.io -u "$QUAY_USERNAME" --password-stdin
    - podman pull $DEV_IMAGE

    - echo "=== TEST ==="
    - podman run -d --name $CONTAINER_NAME --network host $DEV_IMAGE
    - sleep 3
    - podman ps
    # 我的容器 由runn而创建，网络是host 模式，所以没有IP地址，直接访问localhost就行了
    # - CONTAINER_IP=$(podman inspect $CONTAINER_NAME --format '{{.NetworkSettings.IPAddress}}')
    # - echo "Container IP - $CONTAINER_IP"
    - podman inspect $CONTAINER_NAME --format '{{json .NetworkSettings}}'
    - podman inspect $CONTAINER_NAME --format '{{.HostConfig.NetworkMode}}'
    - podman logs $CONTAINER_NAME
    - curl -v http://localhost:80
    - |
      RESULT=$(curl -s http://localhost:80)
      echo "Response: $RESULT"
      echo "$RESULT" | grep -q "Hello, This is Yahoon's ArgoCD Demo from Local GitLab!" \
        && echo "✅ Test passed" \
        || (echo "❌ Test failed" && exit 1)
    - podman tag $DEV_IMAGE $RC_IMAGE
    - podman push $RC_IMAGE
    - echo "✅ Pushed $RC_IMAGE"
  after_script:
    - podman rm -f $CONTAINER_NAME || true
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

push:
  stage: push
  before_script:
    - IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - RC_IMAGE=${IMAGE_NAME}:rc-${IMAGE_TAG}
    - FINAL_IMAGE=${IMAGE_NAME}:${IMAGE_TAG}
    - echo "RC_IMAGE=$RC_IMAGE"
    - echo "FINAL_IMAGE=$FINAL_IMAGE"
  script:
    - echo "=== PULL RC IMAGE ==="
    - echo "$QUAY_PASSWORD" | podman login quay.io -u "$QUAY_USERNAME" --password-stdin
    - podman pull $RC_IMAGE
    - echo "=== RETAG TO FINAL ==="
    - podman tag $RC_IMAGE $FINAL_IMAGE
    - podman push $FINAL_IMAGE
    - echo "✅ Pushed $FINAL_IMAGE"
  rules:
    - if: $CI_COMMIT_TAG