stages:
  - build-test
  - push

default:
  tags:
    - shared-podman
  image: quay.io/containers/podman:latest
  # before_script:
  #   - chmod -R go-w ${PWD}
  #   - git config --global --add safe.directory ${PWD}

variables:
  IMAGE_NAME: quay.io/yahoon/argocd-demo-gl
  CONTAINERFILE_PATH: container-image/argocd-demo/Containerfile
  CONTEXT_PATH: container-image/argocd-demo
  CONTAINER_NAME: argocd-demo-test

before_script:
  - IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
  - IMAGE_FULL=${IMAGE_NAME}:${IMAGE_TAG}
  - echo "IMAGE_FULL=$IMAGE_FULL"

build-test:
  stage: build-test
  script:
    # Build the image
    - echo "Building image $IMAGE_FULL"
    - podman build -f $CONTAINERFILE_PATH -t $IMAGE_FULL $CONTEXT_PATH
    # Test the image
    - echo "Testing image $IMAGE_FULL by curl"
    - podman run -d --name $CONTAINER_NAME $IMAGE_FULL
    - sleep 3
    - podman ps
    - CONTAINER_IP=$(podman inspect $CONTAINER_NAME --format '{{.NetworkSettings.IPAddress}}')
    - podman inspect $CONTAINER_NAME --format '{{json .NetworkSettings}}'
    - podman inspect $CONTAINER_NAME --format '{{.HostConfig.NetworkMode}}'
    - echo "Container IP - $CONTAINER_IP"
    - curl -v http://$CONTAINER_IP:80
    - podman logs $CONTAINER_NAME
    - |
      RESULT=$(curl -s http://$CONTAINER_IP:80)
      echo "Response: $RESULT"
      echo "$RESULT" | grep -q "Hello, This is Yahoon's ArgoCD Demo from Local GitLab!" \
        && echo "✅ Test passed" \
        || (echo "❌ Test failed" && exit 1)
  after_script:
    - podman rm -f $CONTAINER_NAME || true
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

push:
  stage: push
  script:
    - echo "Pushing image $IMAGE_FULL to quay.io"
    - echo "$QUAY_PASSWORD" | podman login quay.io -u "$QUAY_USERNAME" --password-stdin
    - podman push $IMAGE_FULL
  rules:
    - if: $CI_COMMIT_TAG